Update do not supress output

diff --git a/update b/update
--- a/update
+++ b/update
@@ -9,10 +9,10 @@ DATAPATH="$BASEPATH/data"
 REPOPATH="$DATAPATH/repos"
 
 update_submodule(){
-    cd "$BASEPATH" > /dev/null || (echo "Couldn't cd in $BASEPATH" >&2 && exit 2)
+    cd "$BASEPATH" || (echo "Couldn't cd in $BASEPATH" >&2 && exit 2)
     git submodule update --remote --merge "$1"
     git add "$1"
-    if  ! git commit --quiet --message "Update submodules $1" 1> /dev/null 2>&1; then
+    if  ! git commit --quiet --message "Update submodules $1"; then
         echo submodule "$1" did not change >&2
     fi
 }
